### PR TITLE
Additional heatmap refactor

### LINKED ISSUE #35: heatmap: Option to transpose the plot
The current "horizontal" layout shows samples in rows, chromosomes in columns. A transposed or "vertical" layout would show samples in columns, chromosomes in rows. (Sometimes this makes a better figure.)

Consider the flags "-t/--transpose" or "-v/--vertical".

### PR DESCRIPTION
**Pull request by tskir**
Based on work by @tetedange13 in #625. Additional changes:
* Reverted to the original colormap specified by `plots.cvg2rgb`
* Added back support for the `do_desaturate` parameter
* Various additional refactoring and cleaning up

Closes #35.

### CODE REVIEW

**Comment by tskir** [comment]
Some test plots, to make sure things still work:

# `heatmap` (defaults)
image

# `heatmap --vertical`
image

# `heatmap --by-bin`
image

# `heatmap --desaturate`
image

# `heatmap -c chr6`
image

**Comment by tskir** [comment]
Thank you once again @tetedange13 for initiating this work! I'm pretty sure that without this impetus coming from you, the heatmap issue wouldn't have been done for many more years :)

**Comment by tetedange13** [comment]
Hi @tskir ,

Very nice idea to create a different ColorMap according to `desaturate` flag
=> More algorithmically efficient to map original log_values against a limited scale, rather than having to transform each of them beforehand

Kind regards.
Felix.

**Comment by tskir** [comment]
All changes from this PR are already incorporated in #625, closing

**Pull request closed without merging**
