### PR TITLE
Extreme GC Fraction filter - mask_bad_bins - fix.py

### PR DESCRIPTION
**Pull request by tsivaarumugam**
#738 : Code change for accommodating skip extreme GC fraction option to switch on/off the filtering out of GC content below 0.3 & above 0.7
cnvkits_branch_0 9 8_function_mask_bad_bins (1).

### CODE REVIEW

**Comment by tsivaarumugam** [comment]
@tetedange13, I have did the minor modifications to the code to accommodate your suggestion for issue #738 . Kindly review and let me know whether the changes can be merged to the master branch. - Thanks

**Comment by tetedange13** [comment]
Hi @tsivaarumugam,
<br>

Thanks for your PR !
=> I submitted a **simpler** one myself (#753) to adress this, with following differences :

* No specific parameter to turn it on/off (both because it requires a lot of code changes + because not sure a lot of people need to disable this GC-content mask ?)
* I only set a single `MASK_GC` value in `params.py` and always perform a symetric filtering [eg.: "0.3"  filters "less than 0.3" and "above (1-0.3)=0.7"]

I suggest we let @etal decide which solution fits best its vision !
<br>

Hope this helps !
Have a nice day.
Felix.

**Comment by etal** [comment]
Hi @tsivaarumugam -- thanks for your patience. I'm reviewing this alongside #753, and I think I might need to combine the two to find a happy medium.

I also made a change related to #379 which was one of the reasons I added this filter originally; if the problem of residual GC bias is smaller now then there's less need for this filter.

**Comment by tsivaarumugam** [comment]
As the PR #753 addressing the same issue has been merged in to the master branch, I am closing this Pull Request. - Thanks

**Pull request closed without merging**
