### PR TITLE
Use conda + travis env grid for CI

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
cc @rmcgibbo @mpharrigan May we have permission to modify  https://github.com/mdtraj/mdtraj/blob/master/devtools/travis-ci/install_miniconda.sh for use in this Apache licensed open source project?

**Comment by kyleabeauchamp** [comment]
OK, this seems to be almost working.  The one thing that is a little hacky is how I install and uninstall the cnvkit package for the dependencies.  The alternative to this is to keep a copy of the conda recipe in this repo that can be used to build the current git head.  See, e.g. https://github.com/pysam-developers/pysam/blob/master/ci/conda-recipe/meta.yaml

**Comment by rmcgibbo** [comment]
sure.

**Comment by kyleabeauchamp** [comment]
Thanks!

**Comment by mpharrigan** [comment]
@rmcgibbo even had the foresight to license everything in there under bsd 

https://github.com/mdtraj/mdtraj/tree/master/devtools#tools-license

**Comment by kyleabeauchamp** [comment]
OK this should be good to go.  Let me know if you have any questions about the logic / flow of the CI.

**Comment by etal** [comment]
This is a huge help. Thanks!

**Pull request merged**
