### PR TITLE
Python3 compatibility and option "ignore_gt_field"

### PR DESCRIPTION
**Pull request by mpschr**
Hi

I have gotten the code to work with python3. I have been able to use the functions `do_call`, `VariantArray.read_vcf` and `CopyNumArray.read` in my python3 jupyter notebook.

I have run the unittests for both python2 and python3 and I think everything works fine by now. I just wanted to let you know in case you are interested in making a pull request - particularly for the python3 compatibility which I think may serve well for more people ;)

Unrelated,  I have added an option to `VariantArray.read_vcf` called `ignore_gt_field` which lets me ignore the GT (genotype) field of the `vcf` file since I have hand-selected the SNPs for ExAC positions and being heterozygous in the matched normal. The original problem is actually, that I have generated the vcf files with `samtools mpileup` and thus I don't even have the GT field in my `.vcf` file. I guess this may be a problem more people may encounter.

Let me know if there are any more questions/doubts or whatsoever

Best,
Michael

### CODE REVIEW

**Comment by mpschr** [comment]
Fix #3

**Comment by etal** [comment]
Wow, thanks, this is great. Do you feel comfortable splitting this pull request into two, one for Python 3 and a separate one for the VCF changes?

**Comment by etal** [comment]
It looks like `setup.py` needs `future` added to the `install_requires` list in order for Travis CI to run the tests successfully.

**Comment by mpschr** [comment]
Oh sure - I forgot the setup.py file.

Let me see how I can make to separate pull requests

**Pull request closed without merging**
