### PR TITLE
Partition array by chrom for Flasso segmentation

### PR DESCRIPTION
**Pull request by giladmishne**
Currently, the array is treated as a single chromosome, which leads to potential missed calls when the event is towards the end of a chromosome (or, in a capture assay, when the event is towards the end of the data available for a particular chrom).

See also https://www.rdocumentation.org/packages/cghFLasso/versions/0.2-1/topics/cghFLasso.ref

### CODE REVIEW

**Comment by etal** [comment]
Great, thanks! Let me look into why there's a merge conflict here...

**Comment by giladmishne** [comment]
Maybe just because I don't have writ permissions to the repo?

**Comment by etal** [comment]
Can you rebase this to the current master branch?

**Comment by etal** [comment]
OK, I see what happened. I've rebased your commit to the current master branch: 7b482953ec2294e69533baf25b75acb88197e8ec

Thanks for this improvement!

**Pull request closed without merging**
